export interface Book {
    id: string;
    title: string;
    author: string;
    category: string;
    price: number;
    discount_price: number | null;
    stock: number;
    image_url: string;
    description: string;
    is_active: boolean;
}

export interface Category {
    id: string;
    name: string;
}

export interface Bundle {
    id: string;
    title: string;
    book_ids: string[];
    original_price: number;
    bundle_price: number;
}

const DB = {
    categories: [
        { id: "novels", name: "روايات" },
        { id: "horror", name: "رعب وتشويق" },
        { id: "self", name: "تنمية ووعي" },
        { id: "religious", name: "ديني وروحاني" },
        { id: "history", name: "تاريخ وسياسة" },
        { id: "philosophy", name: "فلسفة وفكر" },
    ],
    books: [
        // Novels (روايات)
        {
            id: "bk001",
            title: "أرض زيكولا",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 65,
            discount_price: 55,
            stock: 120,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=أرض+زيكولا",
            description: "رواية خيالية اجتماعية شهيرة تدور أحداثها في قرية يتعامل أهلها بوحدات الذكاء بدلاً من المال.",
            is_active: true,
        },
        {
            id: "bk002",
            title: "أماريتا",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 70,
            discount_price: null,
            stock: 90,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=أماريتا",
            description: "الجزء الثاني من أرض زيكولا، تستكمل رحلة خالد في عوالم غريبة.",
            is_active: true,
        },
        {
            id: "bk003",
            title: "قواعد جارتين",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 75,
            discount_price: 65,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=قواعد+جارتين",
            description: "الجزء الأول من ثلاثية قواعد جارتين، عالم ديستوبي بقوانين صارمة.",
            is_active: true,
        },
        {
            id: "bk004",
            title: "دقات الشامو",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 80,
            discount_price: null,
            stock: 85,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=دقات+الشامو",
            description: "الجزء الثاني من ثلاثية قواعد جارتين.",
            is_active: true,
        },
        {
            id: "bk005",
            title: "أمواج أكما",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 85,
            discount_price: 70,
            stock: 95,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=أمواج+أكما",
            description: "الجزء الثالث والأخير من ثلاثية قواعد جارتين.",
            is_active: true,
        },
        {
            id: "bk006",
            title: "الفيل الأزرق",
            author: "أحمد مراد",
            category: "novels",
            price: 90,
            discount_price: 75,
            stock: 150,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الفيل+الأزرق",
            description: "رواية غموض وإثارة نفسية تحولت لفيلم شهير.",
            is_active: true,
        },
        {
            id: "bk007",
            title: "تراب الماس",
            author: "أحمد مراد",
            category: "novels",
            price: 85,
            discount_price: null,
            stock: 110,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=تراب+الماس",
            description: "جريمة وغموض في أروقة التاريخ المصري الحديث.",
            is_active: true,
        },
        {
            id: "bk008",
            title: "1919",
            author: "أحمد مراد",
            category: "novels",
            price: 95,
            discount_price: 80,
            stock: 130,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=1919",
            description: "رواية تاريخية عن ثورة 1919 وأبطال المقاومة السرية.",
            is_active: true,
        },
        {
            id: "bk009",
            title: "يوتوبيا",
            author: "أحمد خالد توفيق",
            category: "novels",
            price: 50,
            discount_price: 40,
            stock: 200,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=يوتوبيا",
            description: "رواية ديستوبية قصيرة تتنبأ بمستقبل مظلم لمصر.",
            is_active: true,
        },
        {
            id: "bk010",
            title: "في ممر الفئران",
            author: "أحمد خالد توفيق",
            category: "novels",
            price: 70,
            discount_price: 60,
            stock: 140,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=في+ممر+الفئران",
            description: "معالجة أطول وأكثر سوداوية لأسطورة أرض الظلام.",
            is_active: true,
        },
        {
            id: "bk011",
            title: "صانع الظلام",
            author: "تامر إبراهيم",
            category: "horror",
            price: 80,
            discount_price: null,
            stock: 70,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=صانع+الظلام",
            description: "رواية رعب وتشويق عن صحفي يكتشف أسراراً مرعبة.",
            is_active: true,
        },
        {
            id: "bk012",
            title: "الليلة الثالثة والعشرون",
            author: "تامر إبراهيم",
            category: "horror",
            price: 75,
            discount_price: 65,
            stock: 60,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الليلة+23",
            description: "الجزء الثاني من ثنائية صانع الظلام.",
            is_active: true,
        },
        {
            id: "bk013",
            title: "حوجن",
            author: "إبراهيم عباس",
            category: "novels",
            price: 60,
            discount_price: null,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=حوجن",
            description: "رواية رومانسية خيالية عن علاقة بين إنسي وجني.",
            is_active: true,
        },
        {
            id: "bk014",
            title: "ساق البامبو",
            author: "سعود السنعوسي",
            category: "novels",
            price: 85,
            discount_price: 75,
            stock: 90,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=ساق+البامبو",
            description: "رواية اجتماعية تناقش قضايا الهوية والانتماء.",
            is_active: true,
        },
        {
            id: "bk015",
            title: "ثلاثية غرناطة",
            author: "رضوى عاشور",
            category: "novels",
            price: 120,
            discount_price: 100,
            stock: 80,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=ثلاثية+غرناطة",
            description: "ملحمة تاريخية عن سقوط الأندلس ومعاناة الموريسكيين.",
            is_active: true,
        },

        // Horror (رعب وتشويق)
        {
            id: "bk016",
            title: "انتخريستوس",
            author: "أحمد خالد مصطفى",
            category: "horror",
            price: 75,
            discount_price: 60,
            stock: 150,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=انتخريستوس",
            description: "رواية تمزج بين التاريخ والخيال والرعب ونظريات المؤامرة.",
            is_active: true,
        },
        {
            id: "bk017",
            title: "انتخريستوس 2",
            author: "أحمد خالد مصطفى",
            category: "horror",
            price: 85,
            discount_price: null,
            stock: 140,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=انتخريستوس+2",
            description: "الجزء الثاني من السلسلة المثيرة للجدل.",
            is_active: true,
        },
        {
            id: "bk018",
            title: "خوف",
            author: "أسامة المسلم",
            category: "horror",
            price: 70,
            discount_price: null,
            stock: 110,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=خوف",
            description: "الجزء الأول من سلسلة خوف، عن عالم الجن والسحر.",
            is_active: true,
        },
        {
            id: "bk019",
            title: "خوف 2",
            author: "أسامة المسلم",
            category: "horror",
            price: 75,
            discount_price: 65,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=خوف+2",
            description: "استكمال لرحلة خوف في العالم السفلي.",
            is_active: true,
        },
        {
            id: "bk020",
            title: "خوف 3",
            author: "أسامة المسلم",
            category: "horror",
            price: 80,
            discount_price: null,
            stock: 90,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=خوف+3",
            description: "الجزء الثالث من السلسلة.",
            is_active: true,
        },
        {
            id: "bk021",
            title: "بساتين عربستان",
            author: "أسامة المسلم",
            category: "horror",
            price: 85,
            discount_price: 75,
            stock: 120,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=بساتين+عربستان",
            description: "ملحمة فانتازيا تاريخية عن الساحرات في الجزيرة العربية.",
            is_active: true,
        },
        {
            id: "bk022",
            title: "عصبة الشياطين",
            author: "أسامة المسلم",
            category: "horror",
            price: 85,
            discount_price: null,
            stock: 115,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=عصبة+الشياطين",
            description: "الجزء الثاني من سلسلة بساتين عربستان.",
            is_active: true,
        },
        {
            id: "bk023",
            title: "رياح هجر",
            author: "أسامة المسلم",
            category: "horror",
            price: 90,
            discount_price: 80,
            stock: 105,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=رياح+هجر",
            description: "الجزء الثالث من بساتين عربستان.",
            is_active: true,
        },
        {
            id: "bk024",
            title: "عرج السنين",
            author: "أسامة المسلم",
            category: "horror",
            price: 90,
            discount_price: null,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=عرج+السنين",
            description: "الجزء الرابع من السلسلة الملحمية.",
            is_active: true,
        },
        {
            id: "bk025",
            title: "الآن أفهم",
            author: "أحمد خالد توفيق",
            category: "horror",
            price: 60,
            discount_price: 50,
            stock: 130,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الآن+أفهم",
            description: "مجموعة قصصية مرعبة ومثيرة.",
            is_active: true,
        },

        // Self-Help (تنمية ووعي)
        {
            id: "bk026",
            title: "العادات الذرية",
            author: "جيمس كلير",
            category: "self",
            price: 80,
            discount_price: 65,
            stock: 200,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=العادات+الذرية",
            description: "منهجية سهلة لبناء عادات جيدة والتخلص من العادات السيئة.",
            is_active: true,
        },
        {
            id: "bk027",
            title: "نظرية الفستق",
            author: "فهد عامر الأحمدي",
            category: "self",
            price: 75,
            discount_price: null,
            stock: 130,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=نظرية+الفستق",
            description: "كتاب سيغير طريقة تفكيرك وحكمك على الأشياء.",
            is_active: true,
        },
        {
            id: "bk028",
            title: "نظرية الفستق 2",
            author: "فهد عامر الأحمدي",
            category: "self",
            price: 80,
            discount_price: 70,
            stock: 120,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=نظرية+الفستق+2",
            description: "استكمال للأفكار الملهمة في الجزء الأول.",
            is_active: true,
        },
        {
            id: "bk029",
            title: "فن اللامبالاة",
            author: "مارك مانسون",
            category: "self",
            price: 70,
            discount_price: 60,
            stock: 150,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=فن+اللامبالاة",
            description: "لعيش حياة تخالف المألوف.",
            is_active: true,
        },
        {
            id: "bk030",
            title: "الأب الغني والأب الفقير",
            author: "روبرت كيوساكي",
            category: "self",
            price: 85,
            discount_price: 75,
            stock: 140,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الأب+الغني",
            description: "أفضل كتاب مالي شخصي على الإطلاق.",
            is_active: true,
        },
        {
            id: "bk031",
            title: "قوة العقل الباطن",
            author: "جوزيف ميرفي",
            category: "self",
            price: 65,
            discount_price: null,
            stock: 110,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=قوة+العقل+الباطن",
            description: "اكتشف القوة الكامنة بداخلك.",
            is_active: true,
        },
        {
            id: "bk032",
            title: "الرقص مع الحياة",
            author: "مهدي الموسوي",
            category: "self",
            price: 60,
            discount_price: 50,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الرقص+مع+الحياة",
            description: "دعوة للفرح والبهجة والحياة الطيبة.",
            is_active: true,
        },
        {
            id: "bk033",
            title: "السماح بالرحيل",
            author: "ديفيد هاوكينز",
            category: "self",
            price: 90,
            discount_price: 80,
            stock: 95,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=السماح+بالرحيل",
            description: "الطريق نحو التسليم والتحرر النفسي.",
            is_active: true,
        },

        // Religious (ديني وروحاني)
        {
            id: "bk034",
            title: "فاتتني صلاة",
            author: "إسلام جمال",
            category: "religious",
            price: 60,
            discount_price: 50,
            stock: 140,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=فاتتني+صلاة",
            description: "لماذا يحافظ البعض على الصلاة ويتركها الكثير؟",
            is_active: true,
        },
        {
            id: "bk035",
            title: "لكنود",
            author: "إسلام جمال",
            category: "religious",
            price: 65,
            discount_price: null,
            stock: 130,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=لكنود",
            description: "كتاب عن الجحود والنكران لنعم الله.",
            is_active: true,
        },
        {
            id: "bk036",
            title: "رسائل من القرآن",
            author: "أدهم شرقاوي",
            category: "religious",
            price: 65,
            discount_price: null,
            stock: 100,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=رسائل+من+القرآن",
            description: "تأملات في آيات القرآن الكريم.",
            is_active: true,
        },
        {
            id: "bk037",
            title: "مع النبي",
            author: "أدهم شرقاوي",
            category: "religious",
            price: 70,
            discount_price: 58,
            stock: 95,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=مع+النبي",
            description: "قصص ومواقف من حياة النبي صلى الله عليه وسلم.",
            is_active: true,
        },
        {
            id: "bk038",
            title: "لأنك الله",
            author: "علي جابر الفيفي",
            category: "religious",
            price: 55,
            discount_price: 45,
            stock: 160,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=لأنك+الله",
            description: "رحلة إلى السماء السابعة.. رحلة إلى أسماء الله الحسنى.",
            is_active: true,
        },
        {
            id: "bk039",
            title: "الرحيق المختوم",
            author: "صفي الرحمن المباركفوري",
            category: "religious",
            price: 80,
            discount_price: null,
            stock: 110,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الرحيق+المختوم",
            description: "بحث في السيرة النبوية على صاحبها أفضل الصلاة والسلام.",
            is_active: true,
        },

        // History & Politics (تاريخ وسياسة)
        {
            id: "bk040",
            title: "مقدمة ابن خلدون",
            author: "ابن خلدون",
            category: "history",
            price: 150,
            discount_price: 120,
            stock: 50,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=مقدمة+ابن+خلدون",
            description: "كتاب العبر وديوان المبتدأ والخبر.",
            is_active: true,
        },
        {
            id: "bk041",
            title: "عبقرية عمر",
            author: "عباس محمود العقاد",
            category: "history",
            price: 60,
            discount_price: null,
            stock: 80,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=عبقرية+عمر",
            description: "دراسة تحليلية لشخصية الفاروق عمر بن الخطاب.",
            is_active: true,
        },
        {
            id: "bk042",
            title: "عبقرية محمد",
            author: "عباس محمود العقاد",
            category: "history",
            price: 60,
            discount_price: 50,
            stock: 85,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=عبقرية+محمد",
            description: "عبقرية الرسول الكريم كإنسان وقائد.",
            is_active: true,
        },
        {
            id: "bk043",
            title: "قصة الحضارة",
            author: "ويل ديورانت",
            category: "history",
            price: 500,
            discount_price: 450,
            stock: 20,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=قصة+الحضارة",
            description: "موسوعة تاريخية شاملة (نسخة مختصرة).",
            is_active: true,
        },
        {
            id: "bk044",
            title: "الأمير",
            author: "ميكافيلي",
            category: "history",
            price: 55,
            discount_price: null,
            stock: 90,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الأمير",
            description: "كتاب في الفقه السياسي.",
            is_active: true,
        },

        // Philosophy (فلسفة وفكر)
        {
            id: "bk045",
            title: "عالم صوفي",
            author: "جوستاين غاردر",
            category: "philosophy",
            price: 95,
            discount_price: 85,
            stock: 75,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=عالم+صوفي",
            description: "رواية حول تاريخ الفلسفة.",
            is_active: true,
        },
        {
            id: "bk046",
            title: "هكذا تكلم زرادشت",
            author: "فريدريك نيتشه",
            category: "philosophy",
            price: 80,
            discount_price: null,
            stock: 60,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=هكذا+تكلم+زرادشت",
            description: "كتاب للجميع ولا أحد.",
            is_active: true,
        },
        {
            id: "bk047",
            title: "الجمهورية",
            author: "أفلاطون",
            category: "philosophy",
            price: 90,
            discount_price: 75,
            stock: 55,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الجمهورية",
            description: "المدينة الفاضلة كما يراها أفلاطون.",
            is_active: true,
        },
        {
            id: "bk048",
            title: "مهزلة العقل البشري",
            author: "علي الوردي",
            category: "philosophy",
            price: 70,
            discount_price: 60,
            stock: 85,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=مهزلة+العقل",
            description: "بحث في الطبيعة البشرية والمجتمع.",
            is_active: true,
        },
        {
            id: "bk049",
            title: "وعاظ السلاطين",
            author: "علي الوردي",
            category: "philosophy",
            price: 75,
            discount_price: null,
            stock: 80,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=وعاظ+السلاطين",
            description: "تحليل اجتماعي للتاريخ الإسلامي.",
            is_active: true,
        },
        {
            id: "bk050",
            title: "الخيميائي",
            author: "باولو كويلو",
            category: "novels",
            price: 60,
            discount_price: 50,
            stock: 180,
            image_url: "https://placehold.co/400x600/18181b/FFF?text=الخيميائي",
            description: "رواية رمزية عن تحقيق الحلم الشخصي.",
            is_active: true,
        },
    ],
    bundles: [
        {
            id: "bundle001",
            title: "باكدج الروايات الأكثر مبيعًا",
            book_ids: ["bk001", "bk002", "bk003"],
            original_price: 210,
            bundle_price: 170,
        },
        {
            id: "bundle002",
            title: "باكدج تطوير الذات",
            book_ids: ["bk026", "bk027", "bk028"],
            original_price: 235,
            bundle_price: 190,
        },
        {
            id: "bundle003",
            title: "باكدج الرعب",
            book_ids: ["bk016", "bk018", "bk021"],
            original_price: 230,
            bundle_price: 185,
        },
    ],
};

export async function getBooks() {
    return DB.books;
}

export async function getBookById(id: string) {
    return DB.books.find((b) => b.id === id);
}

export async function getCategories() {
    return DB.categories;
}

export async function getBundles() {
    return DB.bundles;
}
