export interface Book {
    id: string;
    title: string;
    author: string;
    category: string;
    price: number;
    discount_price: number | null;
    stock: number;
    image_url: string;
    description: string;
    is_active: boolean;
}

export interface Category {
    id: string;
    name: string;
}

export const DB = {
    categories: [
        { id: "novels", name: "روايات وأدب" },
        { id: "horror", name: "رعب وفانتازيا" },
        { id: "self", name: "تنمية وعلم نفس" },
        { id: "religious", name: "ديني وروحاني" },
        { id: "history", name: "تاريخ وفلسفة" },
    ],
    books: [
        // --- الأدب الكلاسيكي والحديث ---
        {
            id: "bk001",
            title: "بين القصرين",
            author: "نجيب محفوظ",
            category: "novels",
            price: 150,
            discount_price: 120,
            stock: 30,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1423403217l/12713709.jpg",
            description: "الجزء الأول من ثلاثية نجيب محفوظ الشهيرة، وهي تؤرخ لحياة أسرة مصرية متوسطة في حارة شعبية، وتجسد الصراع بين التقاليد الصارمة والتحولات السياسية إبان ثورة 1919.",
            is_active: true,
        },
        {
            id: "bk002",
            title: "الفيل الأزرق",
            author: "أحمد مراد",
            category: "novels",
            price: 100,
            discount_price: 85,
            stock: 150,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1351253457l/16104433.jpg",
            description: "بعد خمس سنوات من العزلة الاختيارية، يعود د. يحيى للعمل في مستشفى العباسية، ليجد نفسه مسؤولاً عن القسم الذي يضم مرتكبي الجرائم، حيث يقابل صديقاً قديماً يجرجر وراءه ماضياً مظلماً.",
            is_active: true,
        },
        {
            id: "bk003",
            title: "أرض زيكولا",
            author: "عمرو عبد الحميد",
            category: "novels",
            price: 75,
            discount_price: 65,
            stock: 200,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1373511675l/18167352.jpg",
            description: "رواية خيالية بطلها خالد الذي يدخل سرداباً في قريته لينتهي به المطاف في أرض زيكولا، حيث يتعامل أهلها بالذكاء بدلاً من المال، ومن ينفد ذكاؤه يُذبح.",
            is_active: true,
        },
        {
            id: "bk004",
            title: "ثلاثية غرناطة",
            author: "رضوى عاشور",
            category: "novels",
            price: 180,
            discount_price: 150,
            stock: 45,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344440626l/15802264.jpg",
            description: "ملحمة تاريخية تتناول حياة عائلة أندلسية على مدى أجيال متعاقبة، منذ سقوط غرناطة عام 1492 وحتى قرار الطرد النهائي للموريسكيين.",
            is_active: true,
        },
        {
            id: "bk005",
            title: "ساق البامبو",
            author: "سعود السنعوسي",
            category: "novels",
            price: 110,
            discount_price: null,
            stock: 60,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1335198030l/13606969.jpg",
            description: "رواية حائزة على جائزة البوكر، تطرح تساؤلات حادة حول الهوية والدين والوطن من خلال قصة عيسى، ابن الخادمة الفلبينية من أب كويتي.",
            is_active: true,
        },

        // --- الرعب والإثارة ---
        {
            id: "bk006",
            title: "انتخريستوس",
            author: "أحمد خالد مصطفى",
            category: "horror",
            price: 90,
            discount_price: 80,
            stock: 250,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1429119561l/25360980.jpg",
            description: "رواية مثيرة للجدل تمزج بين الوقائع التاريخية ونظريات المؤامرة، تأخذك في رحلة عبر الزمن لتعرف أسرار نشأة الماسونية وشياطين بابل.",
            is_active: true,
        },
        {
            id: "bk007",
            title: "خوف",
            author: "أسامة المسلم",
            category: "horror",
            price: 85,
            discount_price: 75,
            stock: 140,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1428526558l/25324536.jpg",
            description: "يسرد الكتاب قصة شاب يدفعه الفضول لاقتحام عالم الجن والسحر، ليكتشف أن الحقيقة أكثر رعباً مما يتخيل، وأن العودة للوراء مستحيلة.",
            is_active: true,
        },
        {
            id: "bk008",
            title: "بساتين عربستان",
            author: "أسامة المسلم",
            category: "horror",
            price: 95,
            discount_price: null,
            stock: 120,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1444155104l/27014605.jpg",
            description: "ملحمة فانتازيا عربية تدور في عصور قديمة، تتناول الصراع الدموي بين ساحرات العرب والانتقام الذي لا ينتهي.",
            is_active: true,
        },

        // --- تطوير الذات وعلم النفس ---
        {
            id: "bk009",
            title: "العادات الذرية",
            author: "جيمس كلير",
            category: "self",
            price: 130,
            discount_price: 110,
            stock: 500,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1647466824l/60619049.jpg",
            description: "الطريقة السهلة والمثبتة لبناء عادات جيدة والتخلص من العادات السيئة، معتمداً على نتائج علمية في السلوك البشري.",
            is_active: true,
        },
        {
            id: "bk010",
            title: "فن اللامبالاة",
            author: "مارك مانسون",
            category: "self",
            price: 95,
            discount_price: 80,
            stock: 300,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1523788734l/39832731.jpg",
            description: "كتاب يساعدك على تحديد ما يهم حقاً في حياتك، والتوقف عن القلق بشأن الأشياء التافهة التي لا تستحق عناء التفكير.",
            is_active: true,
        },
        {
            id: "bk011",
            title: "نظرية الفستق",
            author: "فهد عامر الأحمدي",
            category: "self",
            price: 80,
            discount_price: null,
            stock: 200,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1489063618l/34419263.jpg",
            description: "كتاب سيغير طريقة تفكيرك، يحتوي على مقالات تهدف لفتح آفاق النجاح، وتطوير السلوك، وتحسين نظرتك للعالم من حولك.",
            is_active: true,
        },

        // --- كتب دينية وروحانية ---
        {
            id: "bk012",
            title: "فاتتني صلاة",
            author: "إسلام جمال",
            category: "religious",
            price: 70,
            discount_price: 60,
            stock: 400,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586550785l/52771801.jpg",
            description: "لماذا يحافظ البعض على الصلاة بينما يتركها الكثير؟ كتاب يخاطب عقلك بأسلوب نفسي شيق ليجعلك تعشق الوقوف بين يدي الله.",
            is_active: true,
        },
        {
            id: "bk013",
            title: "لأنك الله",
            author: "علي جابر الفيفي",
            category: "religious",
            price: 65,
            discount_price: null,
            stock: 350,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1471374526l/31448889.jpg",
            description: "رحلة روحانية لاستكشاف معاني أسماء الله الحسنى، وكيف تتجلى رحمته وقدرته في أدق تفاصيل حياتنا اليومية.",
            is_active: true,
        },

        // --- التاريخ والفلسفة ---
        {
            id: "bk014",
            title: "مقدمة ابن خلدون",
            author: "ابن خلدون",
            category: "history",
            price: 300,
            discount_price: 250,
            stock: 20,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1381310618l/13596001.jpg",
            description: "الكتاب الذي وضع حجر الأساس لعلم الاجتماع، يحلل فيه ابن خلدون طبائع العمران، وتطور الدول، وأسباب سقوط الحضارات.",
            is_active: true,
        },
        {
            id: "bk015",
            title: "عالم صوفي",
            author: "جوستاين غاردر",
            category: "philosophy",
            price: 150,
            discount_price: 130,
            stock: 55,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1454580214l/12711776.jpg",
            description: "رواية تأخذك في رحلة تاريخية عبر الفلسفة، من سقراط وأفلاطون حتى الوجودية، في قالب قصصي غامض وممتع.",
            is_active: true,
        },
        {
            id: "bk016",
            title: "هكذا تكلم زرادشت",
            author: "فريدريك نيتشه",
            category: "philosophy",
            price: 120,
            discount_price: null,
            stock: 40,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344265449l/13593006.jpg",
            description: "أحد أهم الكتب الفلسفية في العصر الحديث، يطرح فيه نيتشه أفكاره حول 'الإنسان الأعلى' وموت القيم القديمة.",
            is_active: true,
        },
        {
            id: "bk017",
            title: "الأيام",
            author: "طه حسين",
            category: "history",
            price: 80,
            discount_price: 65,
            stock: 100,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1363623912l/17666275.jpg",
            description: "السيرة الذاتية لعميد الأدب العربي طه حسين، يروي فيها معاناته مع العمى، ورحلته من القرية إلى الأزهر ثم السوربون.",
            is_active: true,
        },
        {
            id: "bk018",
            title: "عنبر الحيتان",
            author: "سعود السنعوسي",
            category: "novels",
            price: 90,
            discount_price: null,
            stock: 70,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1512406830l/36971161.jpg",
            description: "رواية تستعرض التحولات الاجتماعية العميقة في منطقة الخليج من خلال بناء درامي مذهل.",
            is_active: true,
        },
        {
            id: "bk019",
            title: "حوار مع صديقي الملحد",
            author: "مصطفى محمود",
            category: "religious",
            price: 55,
            discount_price: 45,
            stock: 150,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1233075218l/5973685.jpg",
            description: "يرد د. مصطفى محمود بأسلوبه العلمي والفلسفي على تساؤلات الملحدين حول الوجود والذات الإلهية.",
            is_active: true,
        },
        {
            id: "bk020",
            title: "الخبز الحافي",
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344440626l/15802264.jpg",
            description: "ملحمة تاريخية تتناول حياة عائلة أندلسية على مدى أجيال متعاقبة، منذ سقوط غرناطة عام 1492 وحتى قرار الطرد النهائي للموريسكيين.",
            is_active: true,
        },
        {
            id: "bk005",
            title: "ساق البامبو",
            author: "سعود السنعوسي",
            category: "novels",
            price: 110,
            discount_price: null,
            stock: 60,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1335198030l/13606969.jpg",
            description: "رواية حائزة على جائزة البوكر، تطرح تساؤلات حادة حول الهوية والدين والوطن من خلال قصة عيسى، ابن الخادمة الفلبينية من أب كويتي.",
            is_active: true,
        },

        // --- الرعب والإثارة ---
        {
            id: "bk006",
            title: "انتخريستوس",
            author: "أحمد خالد مصطفى",
            category: "horror",
            price: 90,
            discount_price: 80,
            stock: 250,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1429119561l/25360980.jpg",
            description: "رواية مثيرة للجدل تمزج بين الوقائع التاريخية ونظريات المؤامرة، تأخذك في رحلة عبر الزمن لتعرف أسرار نشأة الماسونية وشياطين بابل.",
            is_active: true,
        },
        {
            id: "bk007",
            title: "خوف",
            author: "أسامة المسلم",
            category: "horror",
            price: 85,
            discount_price: 75,
            stock: 140,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1428526558l/25324536.jpg",
            description: "يسرد الكتاب قصة شاب يدفعه الفضول لاقتحام عالم الجن والسحر، ليكتشف أن الحقيقة أكثر رعباً مما يتخيل، وأن العودة للوراء مستحيلة.",
            is_active: true,
        },
        {
            id: "bk008",
            title: "بساتين عربستان",
            author: "أسامة المسلم",
            category: "horror",
            price: 95,
            discount_price: null,
            stock: 120,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1444155104l/27014605.jpg",
            description: "ملحمة فانتازيا عربية تدور في عصور قديمة، تتناول الصراع الدموي بين ساحرات العرب والانتقام الذي لا ينتهي.",
            is_active: true,
        },

        // --- تطوير الذات وعلم النفس ---
        {
            id: "bk009",
            title: "العادات الذرية",
            author: "جيمس كلير",
            category: "self",
            price: 130,
            discount_price: 110,
            stock: 500,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1647466824l/60619049.jpg",
            description: "الطريقة السهلة والمثبتة لبناء عادات جيدة والتخلص من العادات السيئة، معتمداً على نتائج علمية في السلوك البشري.",
            is_active: true,
        },
        {
            id: "bk010",
            title: "فن اللامبالاة",
            author: "مارك مانسون",
            category: "self",
            price: 95,
            discount_price: 80,
            stock: 300,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1523788734l/39832731.jpg",
            description: "كتاب يساعدك على تحديد ما يهم حقاً في حياتك، والتوقف عن القلق بشأن الأشياء التافهة التي لا تستحق عناء التفكير.",
            is_active: true,
        },
        {
            id: "bk011",
            title: "نظرية الفستق",
            author: "فهد عامر الأحمدي",
            category: "self",
            price: 80,
            discount_price: null,
            stock: 200,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1489063618l/34419263.jpg",
            description: "كتاب سيغير طريقة تفكيرك، يحتوي على مقالات تهدف لفتح آفاق النجاح، وتطوير السلوك، وتحسين نظرتك للعالم من حولك.",
            is_active: true,
        },

        // --- كتب دينية وروحانية ---
        {
            id: "bk012",
            title: "فاتتني صلاة",
            author: "إسلام جمال",
            category: "religious",
            price: 70,
            discount_price: 60,
            stock: 400,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586550785l/52771801.jpg",
            description: "لماذا يحافظ البعض على الصلاة بينما يتركها الكثير؟ كتاب يخاطب عقلك بأسلوب نفسي شيق ليجعلك تعشق الوقوف بين يدي الله.",
            is_active: true,
        },
        {
            id: "bk013",
            title: "لأنك الله",
            author: "علي جابر الفيفي",
            category: "religious",
            price: 65,
            discount_price: null,
            stock: 350,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1471374526l/31448889.jpg",
            description: "رحلة روحانية لاستكشاف معاني أسماء الله الحسنى، وكيف تتجلى رحمته وقدرته في أدق تفاصيل حياتنا اليومية.",
            is_active: true,
        },

        // --- التاريخ والفلسفة ---
        {
            id: "bk014",
            title: "مقدمة ابن خلدون",
            author: "ابن خلدون",
            category: "history",
            price: 300,
            discount_price: 250,
            stock: 20,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1381310618l/13596001.jpg",
            description: "الكتاب الذي وضع حجر الأساس لعلم الاجتماع، يحلل فيه ابن خلدون طبائع العمران، وتطور الدول، وأسباب سقوط الحضارات.",
            is_active: true,
        },
        {
            id: "bk015",
            title: "عالم صوفي",
            author: "جوستاين غاردر",
            category: "philosophy",
            price: 150,
            discount_price: 130,
            stock: 55,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1454580214l/12711776.jpg",
            description: "رواية تأخذك في رحلة تاريخية عبر الفلسفة، من سقراط وأفلاطون حتى الوجودية، في قالب قصصي غامض وممتع.",
            is_active: true,
        },
        {
            id: "bk016",
            title: "هكذا تكلم زرادشت",
            author: "فريدريك نيتشه",
            category: "philosophy",
            price: 120,
            discount_price: null,
            stock: 40,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1344265449l/13593006.jpg",
            description: "أحد أهم الكتب الفلسفية في العصر الحديث، يطرح فيه نيتشه أفكاره حول 'الإنسان الأعلى' وموت القيم القديمة.",
            is_active: true,
        },
        {
            id: "bk017",
            title: "الأيام",
            author: "طه حسين",
            category: "history",
            price: 80,
            discount_price: 65,
            stock: 100,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1363623912l/17666275.jpg",
            description: "السيرة الذاتية لعميد الأدب العربي طه حسين، يروي فيها معاناته مع العمى، ورحلته من القرية إلى الأزهر ثم السوربون.",
            is_active: true,
        },
        {
            id: "bk018",
            title: "عنبر الحيتان",
            author: "سعود السنعوسي",
            category: "novels",
            price: 90,
            discount_price: null,
            stock: 70,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1512406830l/36971161.jpg",
            description: "رواية تستعرض التحولات الاجتماعية العميقة في منطقة الخليج من خلال بناء درامي مذهل.",
            is_active: true,
        },
        {
            id: "bk019",
            title: "حوار مع صديقي الملحد",
            author: "مصطفى محمود",
            category: "religious",
            price: 55,
            discount_price: 45,
            stock: 150,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1233075218l/5973685.jpg",
            description: "يرد د. مصطفى محمود بأسلوبه العلمي والفلسفي على تساؤلات الملحدين حول الوجود والذات الإلهية.",
            is_active: true,
        },
        {
            id: "bk020",
            title: "الخبز الحافي",
            author: "محمد شكري",
            category: "novels",
            price: 95,
            discount_price: null,
            stock: 50,
            image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1281223961l/8526563.jpg",
            description: "سيرة ذاتية جريئة وصادمة ترصد حياة الفقر والتشرد في شوارع طنجة خلال الحقبة الاستعمارية.",
            is_active: true,
        }
    ]
};

export async function getBooks() { return DB.books; }
export async function getBookById(id: string) { return DB.books.find((b) => b.id === id); }

export async function getCategories() {
    return DB.categories;
}